package exception;
import java.util.*;

public class ExceptionMain {
   
                	static void compute (int n) throws MyException{
                		System.out.println("called compute " + 10);
                		
                		if(n>10)
                		{
                			throw new MyException(n);
                		}
                		System.out.println("normal exit");
                	}
                	static Scanner s  = new Scanner(System.in);
                	
                	public static void main(String args[])
                	{ 
                		int a  = s.nextInt();
                		int b = s.nextInt();
                		
                		try
                		{
                			compute(a);
                			compute(b);
                		}
                		catch (MyException e)
                		{
                			System.out.println("caught " + e);
                		}
                	}
                
}
